client_s: client_s.c helper.c comm.c cli_args.c
	clang -o client_s client_s.c helper.c comm.c cli_args.c -lhiredis -luuid -std=c11

client_l_m: client_l_m.c helper.c comm.c cli_args.c
	clang -o client_l_m client_l_m.c helper.c comm.c cli_args.c -lhiredis -luuid -std=c11

client_l_u: client_l_u.c helper.c comm.c cli_args.c
	clang -o client_l_u client_l_u.c helper.c comm.c cli_args.c -lhiredis -luuid -std=c11