client_s: client_s.c helper.c comm.c cli_args.c
	gcc -o client_s client_s.c helper.c comm.c cli_args.c -lhiredis -luuid --std=c11 -Wall -Wextra -pedantic -D_POSIX_C_SOURCE=200809

client_l_m: client_l_m.c helper.c comm.c cli_args.c
	gcc -o client_l_m client_l_m.c helper.c comm.c cli_args.c -lhiredis -luuid --std=c11 -Wall -Wextra -pedantic -D_POSIX_C_SOURCE=200809

client_l_u: client_l_u.c helper.c comm.c cli_args.c
	gcc -o client_l_u client_l_u.c helper.c comm.c cli_args.c -lhiredis -luuid --std=c11 -Wall -Wextra -pedantic -D_POSIX_C_SOURCE=200809
